### ISSUE TITLE
Mac 下不成功

### ISSUE THREAD

**Issue by d-hu-x** [XanderYe/tmm-cracker#1]
版本4.0.6 替换原有tmm.jar之后，启动时出现如下错误信息。

java.lang.NoClassDefFoundError: org/tinymediamanager/license/nuL
	at org.tinymediamanager.license.MovieEventList.<init>(Unknown Source)
	at org.tinymediamanager.core.movie.MovieList.<init>(MovieList.java:118)
	at org.tinymediamanager.core.movie.MovieList.getInstance(MovieList.java:196)
	at org.tinymediamanager.core.movie.MovieModuleManager.startUp(MovieModuleManager.java:139)
	at org.tinymediamanager.core.TmmModuleManager.enableModule(TmmModuleManager.java:57)
	at org.tinymediamanager.TinyMediaManager$1.run(TinyMediaManager.java:274)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.tinymediamanager.license.nuL
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more

**Comment by XanderYe** [comment]
此问题由于macos默认大小写不敏感导致，已存在Nul文件时解压nuL失败，导致打包后丢失类文件。建议使用linux执行
