### ISSUE TITLE
在Ubuntu下执行报错

### ISSUE THREAD

**Issue by PanZK** [XanderYe/tmm-cracker#2]
执行
`java -jar tmm-cracker-jar-with-dependencies.jar`
的时候报错：
解压jar
java.io.IOException: Cannot run program "jar": error=2, 没有那个文件或目录
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at cn.xanderye.util.SystemUtil.execStr(SystemUtil.java:63)
	at cn.xanderye.util.TmmCrackUtil.uncompress(TmmCrackUtil.java:27)
	at cn.xanderye.Main.main(Main.java:27)
Caused by: java.io.IOException: error=2, 没有那个文件或目录
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 4 more
去除授权校验
去除检测更新

**Comment by XanderYe** [comment]
jar命令是jdk的不是jre的，确认下jar命令是否可用，不能用的话看下环境变量，应该是没配置好
