### ISSUE TITLE
not working anymore?

### ISSUE THREAD

**Issue by azeunkn0wn** [XanderYe/tmm-cracker#6]
no longer work with tmm v4.3.5 or am I doing something wrong?

`sudo java -jar tmm-cracker-jar-with-dependencies.jar tmm-cracked.jar

解压jar
去除授权校验
javassist.NotFoundException: org.tinymediamanager.license.Nul
        at javassist.ClassPool.get(ClassPool.java:430)
        at javassist.ClassPool.getCtClass(ClassPool.java:495)
        at cn.xanderye.Main.main(Main.java:30)
`

**Comment by XanderYe** [comment]
Yes, it can only work with tmm v4.0.6.
